Crown-Commercial-Service/conclave-cii-api

.travis.yml
manifest.yml

Updated manifest file and travis

---

.travis.yml
app/services/common/additional_identifier.rb
app/services/common/api_helper.rb
app/services/companies_house/address.rb
app/services/dnb/additional_identifier.rb
app/services/dnb/address.rb
app/services/dnb/search.rb
app/services/find_that_charity/additional_identifier.rb
app/services/find_that_charity/address.rb
app/services/find_that_charity/search.rb
app/services/search_api.rb

CII-Jira-Con-470
CII-Jira-Con-536
CII-Jira-Con-439

CII-Jira-Con-470

---

CF/manifest-template.yml
Gemfile
Gemfile.lock
config/initializers/rollbar.rb

Con 409 rollbar setup

---

.travis.yml
CF/manifest-template.yml

Staging branch into integration

Staging branch into integration

---

.travis.yml

Test coverage setup for climate

added code climate coverage

---

app/controllers/api/v1/create_organisations_controller.rb
app/controllers/api/v1/multiple_organisations_controller.rb
app/controllers/api/v1/organisations_controller.rb
app/services/api_validations/api_error.rb
app/services/api_validations/api_error_validation_response.rb
app/services/api_validations/create_organisation.rb
app/services/api_validations/organisation.rb
app/services/api_validations/scheme.rb
app/services/authorize/token.rb
app/services/common/status_codes.rb
app/services/search_api.rb

Status codes updated

---

app/controllers/api/v1/create_organisations_controller.rb

Fixed 500 error now should show 404

Update Post call http status fix

---

app/controllers/api/v1/remove_organisations_aditional_identifier_controller.rb
app/controllers/api/v1/remove_organisations_controller.rb
app/services/api_validations/api_error_validation_response.rb
app/services/api_validations/remove_organisation.rb
app/services/api_validations/remove_organisation_aditional_identifier.rb
app/services/api_validations/remove_scheme.rb
app/services/companies_house/address.rb
config/routes.rb
db/seeds.rb

Created delete endpoints for CII

Jira con 245 and Jira Con 439

---

.travis.yml
CF/deploy-app.sh

adding rolling deploy and edge placement

---

.travis.yml
CF/deploy-app.sh

removed edge

---

.travis.yml

updating cf7

---

app/controllers/api/v1/update_organisations_controller.rb
app/services/api_validations/update_organisation.rb

CON-620-PUT-Bug-Fixes

---

app/controllers/api/v1/create_organisations_controller.rb
app/services/common/api_helper.rb
app/services/find_that_charity/search.rb
app/services/search_api.rb

Filter scottish charity
Check duplication

Jira-con-560-533-543

---

app/services/find_that_charity/identifier.rb
app/services/find_that_charity/search.rb

Adds the correct uri value to the identifier on scheme id search.

Con 556-Response-URI

---

app/controllers/api/v1/update_organisations_controller.rb
app/services/api_validations/scheme.rb
app/services/common/api_helper.rb
app/services/search_api.rb

Jira-649-627
PUT request now checks duplicate record if not the same orginisation
SC|NIC cahrities prefix added by default.

Jira-649-627

---

app/services/api_validations/api_error_validation_response.rb
app/services/api_validations/remove_scheme.rb
app/services/find_that_charity/search.rb

Fixed updates for these tickets
Delete Fixed response payload
Removed addistionsl identifiers for charity from links

Con-627-con-611

---

CF/manifest-template.yml

servcie bind for splunk ( setup done in GPAAS)

integrated splunk for logs

---

CF/manifest-template.yml

no more dynamic url generation when we deploy app to CF

private deploy to CF

---

app/controllers/api/v1/manage_organisations_controller.rb
app/services/api_validations/manage_organisation.rb

Changed parameters for the endpoint

Jira-660 update endpoints

---

app/controllers/api/v1/all_registered_organisations_schemes_controller.rb
app/controllers/api/v1/create_organisations_controller.rb
app/controllers/api/v1/testing/crud_testing_controller.rb
app/services/common/registered_organisation_response.rb
config/routes.rb
db/migrate/20210302165511_add_active_to_organisation_scheme_identifiers.rb
db/schema.rb

New endpoints all
save additional identifiers even if not selected by user

Jira-612-Jira-270

---

app/services/companies_house/search.rb
app/services/dnb/search.rb
app/services/find_that_charity/search.rb
spec/stub_response/companies_house_api.json
spec/stub_response/dandb_api.json

Returns only Active Business'/Organisations, in returns

CON-656-672-699-Active-Status-Returned

---

CF/deploy-app.sh

Remove-rolling

---

config/initializers/cf_vault.rb

Update cf_vault.rb to debug vault credentials

---

config/initializers/cf_vault.rb

Update cf_vault.rb Revert debug changes

---

app/services/companies_house/search.rb
app/services/find_that_charity/search.rb
spec/stub_response/companies_house_api.json

Fix COH to return only active status companies

Fix COH to return only active status companies

---

app/controllers/api/v1/update_organisations_controller.rb

Quick fix for update endpoint on Integration

---

app/controllers/api/v1/create_organisations_controller.rb
app/controllers/api/v1/schemes_controller.rb
app/controllers/api/v1/update_organisations_controller.rb
app/services/common/salesforce_helper.rb
app/services/search_api.rb

Jira-494 salesforce integration

---

app/controllers/api/v1/all_registered_organisations_schemes_controller.rb
app/controllers/api/v1/manage_organisations_controller.rb
app/controllers/api/v1/registered_organisations_schemes_controller.rb
app/controllers/api/v1/remove_organisations_aditional_identifier_controller.rb
app/controllers/api/v1/update_organisations_controller.rb
app/services/api_validations/api_error_validation_response.rb
app/services/authorize/user.rb
app/services/common/api_helper.rb
app/services/security_service/auth.rb
spec/controllers/api/v1/all_registered_organisations_schemes_controller_spec.rb
spec/controllers/api/v1/manage_organisations_controller_spec.rb
spec/controllers/api/v1/registered_organisations_schemes_controller_spec.rb
spec/controllers/api/v1/remove_organisations_aditional_identifier_controller_spec.rb
spec/controllers/api/v1/update_organisations_controller_spec.rb
spec/services/api_validations/api_error_validation_response_spec.rb
spec/services/api_validations/scheme_spec.rb

Security service Authentication

---

spec/stub_response/api_stubs/GB-CHC-707123.json
spec/stub_response/api_stubs/GB-SC-SC201234.json

Minor-Stub-Data-Change

---

spec/stub_response/api_stubs/GB-SC-SC201234.json

Fix missing ID, in stub GB-SC-201234

Fix missing ID, in stub GB-SC-201234

---

app/services/authorize/token.rb
spec/controllers/api/v1/buyer_registration_controller_spec.rb
spec/controllers/api/v1/manage_organisations_controller_spec.rb
spec/controllers/api/v1/organisations_controller_spec.rb
spec/controllers/api/v1/registered_organisations_schemes_controller_spec.rb
spec/controllers/api/v1/remove_organisations_additional_identifier_controller_spec.rb
spec/controllers/api/v1/remove_organisations_controller_spec.rb
spec/controllers/api/v1/schemes_controller_spec.rb
spec/controllers/api/v1/update_organisations_controller_spec.rb
spec/stubs/create_organisations_mock_controller_spec.rb

Removed Apikey header

---

app/controllers/api/v1/all_registered_organisations_schemes_controller.rb
app/controllers/api/v1/buyer_registration_controller.rb
app/controllers/api/v1/create_organisations_controller.rb
app/controllers/api/v1/testing/crud_testing_controller.rb
app/controllers/api/v1/update_organisations_controller.rb
app/services/common/registered_organisation_response.rb
app/services/common/salesforce_helper.rb
app/services/salesforce/additional_identifier.rb
db/migrate/20210302165511_add_active_to_organisation_scheme_identifiers.rb
db/schema.rb
spec/factories/organisation_scheme_identifier.rb

910 - Change 'active' to 'hidden'
980, 981 - In the event an org has two Salesforce ID's (using both US-DUN and GB-COH), add both to CII

CON-910-980-981

---

config/initializers/cf_vault.rb
db/migrate/20210302165511_add_active_to_organisation_scheme_identifiers.rb
db/migrate/20210511175222_rename_active_to_hidden_organisation_scheme_identifiers.rb
db/schema.rb

Fix Migration.
Remove default rollbar initialize.

Fix Migration | Rollbar

---

.travis.yml
CF/deploy-app.sh

pre production settings for deployment

---

CF/deploy-app.sh

Updated pre production memory limit

Pre production memory limit updated

---

app/services/api_validations/scheme.rb
app/services/common/api_helper.rb
app/services/common/status_codes.rb
config/routes.rb
spec/controllers/api/v1/all_registered_organisations_schemes_controller_spec.rb
spec/controllers/api/v1/remove_organisations_additional_identifier_controller_spec.rb
spec/controllers/api/v1/update_organisations_controller_spec.rb
spec/stubs/create_organisations_mock_controller_spec.rb

Fixed jira-con-871

---

app/controllers/api/v1/buyer_registration_controller.rb
app/controllers/api/v1/create_organisations_controller.rb

Implemented ticket details to validate schemes duplication

Jira con 1084

---

app/controllers/api/v1/buyer_registration_controller.rb
app/services/api_validations/scheme.rb

https://crowncommercialservice.atlassian.net/browse/CON-1318

CON-1318-Issue-#2-ID-Not-Returned-Fix

---

app/controllers/api/v1/buyer_registration_controller.rb

https://crowncommercialservice.atlassian.net/browse/CON-1314

CON-1314-Regression-Issues

---

app/controllers/api/v1/buyer_registration_controller.rb
app/services/search_api.rb

https://crowncommercialservice.atlassian.net/browse/CON-1314

CON-1214-Fix-New-Bugs

---

app/controllers/api/v1/buyer_registration_controller.rb
app/services/common/address_helper.rb
app/services/common/contact_helper.rb

https://crowncommercialservice.atlassian.net/browse/CON-1314

CON-1314-Fix-Contact-500-Err

---

app/controllers/api/v1/buyer_registration_controller.rb
app/services/api_validations/api_error_validation_response.rb
app/services/api_validations/scheme.rb
app/services/search_api.rb

https://crowncommercialservice.atlassian.net/browse/CON-1318
The final fix for the Data Migration endpoint, meaning it is finished!

CON-1318-Org-ID-Not-Returning-Fix

---

.travis.yml
CF/deploy-app.sh

https://crowncommercialservice.atlassian.net/browse/CON-1362

CON-1362-Add-UAT-To-Deployment-Pipeline

---

.travis.yml
CF/deploy-app.sh

https://crowncommercialservice.atlassian.net/browse/CON-1362

Merge int into uat

---

app/controllers/api/v1/buyer_registration_controller.rb

https://crowncommercialservice.atlassian.net/browse/CON-1318

CON-1318-SF-CCS-Org-Null-Fix

---

spec/stub_response/api_salesforce/sf-id-NSO7IUSHF98HFP9WEH9FHE.json
spec/stub_response/api_salesforce/sf-id-NSO7IUSHF98HFP9WEH9FNQ.json
spec/stub_response/api_salesforce/sf-id-NSO7IUSHF98HFP9WEH9FQZ.json
spec/stub_response/api_salesforce/sf-urn-66650000001.json
spec/stub_response/api_salesforce/sf-urn-66650000002.json
spec/stub_response/api_salesforce/sf-urn-66650000003.json
spec/stub_response/salesforce/GB-COH-07612345.json
spec/stub_response/salesforce/GB-COH-09012345.json
spec/stub_response/salesforce/US-DUN-404123456.json
spec/stub_response/salesforce/US-DUN-505123456.json

Amrutha needed some minor changes to the mocked data.

CON-1349-Mock-Data-Update

---

app/controllers/api/v1/data_migration_controller.rb

https://crowncommercialservice.atlassian.net/browse/CON-1454

CON-1454-Minor-Bug-Fix

---

app/services/security_service/auth.rb
spec/controllers/api/v1/all_registered_organisations_schemes_controller_spec.rb
spec/controllers/api/v1/manage_organisations_controller_spec.rb
spec/controllers/api/v1/registered_organisations_schemes_controller_spec.rb
spec/controllers/api/v1/remove_organisations_additional_identifier_controller_spec.rb
spec/controllers/api/v1/update_organisations_controller_spec.rb

Reverts Crown-Commercial-Service/conclave-cii-api#326 - unneeded due to some miscommunication.

Revert "Merge test into int"

---

app/controllers/api/v1/create_organisations_controller.rb
app/controllers/api/v1/update_organisations_controller.rb
spec/controllers/api/v1/create_organisations_controller_spec.rb

https://crowncommercialservice.atlassian.net/browse/CON-1585

CON-1585-Replaces-CCS-Org-Id-Naming-Conventions

---

app/controllers/api/v1/all_registered_organisations_schemes_controller.rb
app/controllers/api/v1/utilities/all_registered_organisations_schemes_controller.rb
app/services/authorize/user.rb
spec/controllers/api/v1/all_registered_organisations_schemes_controller_spec.rb

https://crowncommercialservice.atlassian.net/browse/CON-1618

CON-1618-Update-Auth-Endpoints

---

app/controllers/api/v1/create_organisations_controller.rb
app/services/api_validations/create_organisation.rb
app/services/api_validations/scheme.rb
app/services/search_api.rb

https://crowncommercialservice.atlassian.net/browse/CON-1733

CON-1733-Organisation-Id-Returned-POST

---

app/controllers/api/v1/organisations_controller.rb

CON-1678-Update-Organisation-Controller-Response

---

app/controllers/api/v1/organisations_controller.rb

CON-1678-Updates-Organisation-Controller-Response

---

app/controllers/api/v1/testing/access_token_controller.rb
config/routes.rb

https://crowncommercialservice.atlassian.net/browse/CON-1166

CON-1166-Test-Access-Token-Endpoint-Added

---

app/controllers/api/v1/data_migration_controller.rb
app/controllers/api/v1/organisations_controller.rb

CON-1678-Fix-Response-Not-Returning-Identifier

---

app/services/authorize/user.rb

https://crowncommercialservice.atlassian.net/browse/CON-1617

CON-1617-Add-Data-Migration-Role

---

app/controllers/api/v1/data_migration_controller.rb
app/controllers/api/v1/organisations_controller.rb
spec/controllers/api/v1/data_migration_controller_spec.rb
spec/controllers/api/v1/organisations_controller_spec.rb

https://crowncommercialservice.atlassian.net/browse/CON-1591

CON-1591-1678-DM Endpoint-Bugfixes-And-Add-Address-To-Response

---

app/controllers/api/v1/organisations_controller.rb

CON-1678-Fix-500-Error-Bug

---

app/controllers/api/v1/organisations_controller.rb
app/controllers/api/v1/registered_organisations_schemes_controller.rb
spec/controllers/api/v1/registered_organisations_schemes_controller_spec.rb

https://crowncommercialservice.atlassian.net/browse/CON-1558

CON-1678-Revert-Changes-And-Add-Address-Response

---

.travis.yml

explicit changes to travis yaml to deploy onto production space

---

CF/manifest-template.yml

splunk servcie named after prod space to deploy

---

app/services/nhs/address.rb
app/services/nhs/contact.rb
db/seeds.rb

https://crowncommercialservice.atlassian.net/browse/CON-2009
https://crowncommercialservice.atlassian.net/browse/CON-2013
https://crowncommercialservice.atlassian.net/browse/CON-2019

CON-2009-2013-2019-NHS-Registry-Service-Updates-And-Access-Token-Test

---

app/controllers/api/v1/testing/access_token_controller.rb

https://crowncommercialservice.atlassian.net/browse/CON-2013

CON-2013-Update-Access-Token-Endpoint

---

.travis.yml
CF/deploy-app.sh

Setup New Pre-Production Deployment.
**Final PR Remaining Today:**
1. Dev -> Test (#384)
2. Test -> Integration (_#385_)
3. Integration -> UAT (_#386_)
4. UAT -> Preproduction (_#388_)
✅ And we're done ✅ 
FYI: https://crowncommercialservice.atlassian.net/browse/CON-2029

Add new preproduction deployment

---

Gemfile
Gemfile.lock
config/initializers/aws_ssm.rb
config/initializers/cf_vault.rb

Added compatibility for AWS SSM - Params Store, which will take over our Vault service.

Add-AWS-SSM-Config-Sandbox

---

Gemfile
Gemfile.lock
config/initializers/aws_ssm.rb

Add the configuration for AWS SSM ParamStore to the development environment

Add-AWS-SSM-Development

---

Gemfile
Gemfile.lock
app/models/export.rb
config/initializers/scheduler.rb

Adds overnight export process to the production environment.

Add export

---

app/controllers/api/v1/registered_organisations_schemes_controller.rb

Remove service eligibility configuration, whilst Brick updates their handling of these changes.

Remove-Manage-Service-Eligibility-Config

---

app/controllers/api/v1/registered_organisations_schemes_controller.rb
app/controllers/api/v1/testing/access_token_controller.rb
app/services/authorize/user.rb
app/services/companies_house/search.rb
app/services/dnb/search.rb
app/services/find_that_charity/search.rb
app/services/mocking_service/api_salesforce_stub.rb
app/services/mocking_service/api_stub.rb
app/services/mocking_service/migration_salesforce_api.rb
app/services/salesforce/search.rb
app/services/security_service/auth.rb
spec/controllers/api/v1/all_registered_organisations_schemes_controller_spec.rb
spec/controllers/api/v1/create_organisations_controller_spec.rb
spec/controllers/api/v1/data_migration_controller_spec.rb
spec/controllers/api/v1/manage_organisations_controller_spec.rb
spec/controllers/api/v1/registered_organisations_schemes_controller_spec.rb
spec/controllers/api/v1/remove_organisations_additional_identifier_controller_spec.rb
spec/controllers/api/v1/update_organisations_controller_spec.rb

**https://crowncommercialservice.atlassian.net/browse/CON-1373**
Add new behavior to registered_organisations_controller to show hidden identifiers, when called by a Service Eligibility user role. Otherwise returns only non-hidden identifiers.

CON-1373-Add-Service-Eligibility-Role-Support

---

app/services/authorize/authorization_methods.rb
app/services/authorize/user.rb

**https://crowncommercialservice.atlassian.net/browse/CON-1373**
Fix a 401 response that we being given when supplying access_token.

CON-1373-Fix-401-MSE-Issue

---

app/services/common/api_helper.rb

Fixes bug, when updating using the test identifier.

CON-Add-DB-Check-For-MockID-Fix-Bug

---

.travis.yml
CF/deploy-app.sh

Adds the new NFT environment to the existing CI/CD deployment pipeline, through Travis.

Add NFT to deployment pipeline

---

.travis.yml
CF/deploy-app.sh
Gemfile.lock
README.md
app/services/authorize/user.rb
app/services/common/api_helper.rb

Merge uat into nft

---

app/services/dfe/address.rb

**https://crowncommercialservice.atlassian.net/browse/CON-1320**
Update handling of country name, when data supplied is incomplete or missing.

CON-1320-Update-Address-Handling

---

app/controllers/api/v1/update_organisations_controller.rb

**https://crowncommercialservice.atlassian.net/browse/PPG-217**
Fix CII PUT call bug, when adding PPON as an additional identifier to organisations in PPG.

PPG-217-Fix-PUT-Endpoint-Bug

---

app/controllers/api/v1/create_organisations_controller.rb
app/controllers/api/v1/manage_organisations_controller.rb
app/controllers/api/v1/organisations_controller.rb

**https://crowncommercialservice.atlassian.net/browse/PPG-252**
Remove PPON CII compatibility.

PPG-252-Fix-CII-PPON-Issues

---

app/controllers/api/v1/remove_organisations_additional_identifier_controller.rb

**https://crowncommercialservice.atlassian.net/browse/PPG-244**
Remove PPON CII compatibility from CII delete endpoint.

PPG-244-Update-CII-Delete-Endpoint-To-Ignore-PPON

---

app/controllers/api/v1/remove_organisations_additional_identifier_controller.rb

**https://crowncommercialservice.atlassian.net/browse/PPG-244**
Update response when PPON scheme is given, in CII delete endpoint.

PPG-244-Update-Delete-Endpoint-Response-On-PPON

---

db/seeds.rb

**https://crowncommercialservice.atlassian.net/browse/PPG-252**
Add PPON seed, so that schemes is populated with a PPON entry.

PPG-252-Add-PPON-To-Schemes-Page

---

db/seeds.rb

**https://crowncommercialservice.atlassian.net/browse/PPG-252**
Updating the registry entry for PPON schemes.

PPG-275-Update-PPON-Seed-Registry-Name

---

app/services/dfe/search.rb

This is to merge DFE cache for ruby 3.2.2

Update DFE search.rb

---

app/controllers/api/v1/data_migration_controller.rb
app/services/authorize/authorization_methods.rb

**https://crowncommercialservice.atlassian.net/browse/PPG-628**
Adds the additional option to authorize DM endpoint API Key.

PPG-628-Add-OR-Authorization-To-DM

---

app/services/dfe/search.rb

A small update to return 503 for DFE registry

Update DFE search

---

app/services/api_validations/api_error_validation_response.rb
app/services/companies_house/search.rb
app/services/dfe/search.rb
app/services/dnb/search.rb
app/services/dnb_chn/search.rb
app/services/find_that_charity/search.rb
app/services/nhs/search.rb
app/services/salesforce/search.rb

Not to break the application flow if one registry has any downtime

Updated api to now handle registry url down

---

app/services/security_service/auth.rb
spec/controllers/api/v1/manage_organisations_controller_spec.rb
spec/controllers/api/v1/remove_organisations_additional_identifier_controller_spec.rb
spec/controllers/api/v1/update_organisations_controller_spec.rb

Update security service method to use env variables, so we can have two different endpoint depending on environment.

Update security service

---

app/services/security_service/auth.rb
spec/controllers/api/v1/manage_organisations_controller_spec.rb
spec/controllers/api/v1/remove_organisations_additional_identifier_controller_spec.rb
spec/controllers/api/v1/update_organisations_controller_spec.rb

Update security service method to use env variables, so we can have two different endpoint depending on environment.

Staging update security service method

---

app/services/security_service/auth.rb
spec/controllers/api/v1/manage_organisations_controller_spec.rb
spec/controllers/api/v1/remove_organisations_additional_identifier_controller_spec.rb
spec/controllers/api/v1/update_organisations_controller_spec.rb

Update security service method to use env variables, so we can have two different endpoint depending on environment.

Int update security service method

---

app/services/security_service/auth.rb
spec/controllers/api/v1/manage_organisations_controller_spec.rb
spec/controllers/api/v1/remove_organisations_additional_identifier_controller_spec.rb
spec/controllers/api/v1/update_organisations_controller_spec.rb

Update security service method to use env variables, so we can have two different endpoint depending on environment.

uat-Update-Security-Service-Method

---

app/services/search_api_additional_identifiers.rb
app/services/spotlight/search.rb

Rename the parameters used in the code to match what is in Param Store.

Fixing spotlight parameter issue and remove logging

---

app/services/spotlight/search.rb

spotlight-add-extra-logging-for-debug

spotlight-add-extra-logging-for-debug

---

app/services/spotlight/search.rb

Fixes remaining Spotlight issues, by accounting for where the external API returns a 200, even though the DnB API itself returns a negative response of 400 Bad Request, with no record/data.
Removes any added logging that was used for debugging the above issues.

Fix Spotlight Issues & Remove Debug Logging
